export type RiskType =
  | 'LIKELY_HIGH_RISK'
  | 'POSSIBLY_HIGH_RISK'
  | 'RISK_UNLIKELY'
  | 'INCOMPLETE_FIELDS'
  | 'USER_DETERMINED_NO_INDICATOR';

export const RISK_TYPE_LABELS = {
  LIKELY_HIGH_RISK: 'Likely High Risk',
  POSSIBLY_HIGH_RISK: 'Possibly High Risk',
  RISK_UNLIKELY: 'Risk Unlikely',
  INCOMPLETE_FIELDS: 'Incomplete Fields',
  USER_DETERMINED_NO_INDICATOR: '--',
  LOW_INHERENT_RISK: 'Low Inherent Risk',
  MEDIUM_INHERENT_RISK: 'Medium Inherent Risk',
  HIGH_INHERENT_RISK: 'High Inherent Risk',
  LOW_RESIDUAL_RISK: 'Low Residual Risk',
  MEDIUM_RESIDUAL_RISK: 'Medium Residual Risk',
  HIGH_RESIDUAL_RISK: 'High Residual Risk'
};

export const RISK_TYPE = {
  LIKELY_HIGH_RISK: 'LIKELY_HIGH_RISK',
  POSSIBLY_HIGH_RISK: 'POSSIBLY_HIGH_RISK',
  RISK_UNLIKELY: 'RISK_UNLIKELY',
  INCOMPLETE_FIELDS: 'INCOMPLETE_FIELDS',
  USER_DETERMINED_NO_INDICATOR: 'USER_DETERMINED_NO_INDICATOR',
  LOW_INHERENT_RISK: 'LOW_INHERENT_RISK',
  MEDIUM_INHERENT_RISK: 'MEDIUM_INHERENT_RISK',
  HIGH_INHERENT_RISK: 'HIGH_INHERENT_RISK',
  LOW_RESIDUAL_RISK: 'LOW_RESIDUAL_RISK',
  MEDIUM_RESIDUAL_RISK: 'MEDIUM_RESIDUAL_RISK',
  HIGH_RESIDUAL_RISK: 'HIGH_RESIDUAL_RISK'
};
