export interface FeatureFlagAllInterface {
  CUSTOMIZATION_DATA_SUBJECTS_LICENSE?: boolean;
  RHEA_FILTER_BY_DATABASE?: boolean;
  RISK_PROFILE_LICENSE?: boolean;
  PRIVACY_SHIELD?: boolean;
  PI_CCPA?: boolean;
  PRIVACY_ASSURANCE?: boolean;
  PI_ALL?: boolean;
  CUSTOMIZATION_DEPARTMENT_LICENSE?: boolean;
  ACCOUNT_INTERNAL?: boolean;
  RHEA_NEW_AUDIT_LOG?: boolean;
  RISK_PROFILE_THIRD_PARTY_LICENSE?: boolean;
  CUSTOMIZATION_DATA_ELEMENT_LICENSE?: boolean;
  RHEA_NEW_UI_STEPS_34_LICENSE?: boolean;
  CUSTOMIZATION_PROCESSING_PURPOSES_LICENSE?: boolean;
  RHEA_NEW_UI_ALL_STEPS_LICENSE?: boolean;
  REPORTING_TRAINING_LICENSE?: boolean;
  RISK_SERVICE_V2?: boolean;
  RHEA_NEW_UI_STEPS_12_LICENSE?: boolean;
}
